### ISSUE TITLE
Support for Schwab [US]

### ISSUE THREAD

**Issue by nocalla** [bank2ynab/bank2ynab#122]
Name of Bank: Schwab
Country: USA

Source: [RichardLitt/ynab-convert-csv](https://github.com/RichardLitt/ynab-convert-csv)

**To be filled in as required. Delete fields that match default values.**
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Plugin =

Master Issue #21

**Comment by torbengb** [comment]
Config based on [this sample file](https://raw.githubusercontent.com/RichardLitt/ynab-convert-csv/master/examples/schwab.csv)

```
[US Schwab]
Use Regex for Filename = ????
Source Filename Pattern = ????
Source Filename Extension = .csv
Header Rows = 3
Footer Rows = 0
Input Columns = Date,skip,skip,Payee,Outflow,Inflow,skip
Date Format = MM/DD/YYYY
```

Transactions  for Checking account XXXXXX-XXXXXX as of 09/01/2017 11:28:39 ET
"Date","Type","Check #","Description","Withdrawal (-)","Deposit (+)","RunningBalance"
"Pending Transactions"
"Total Pending Check and other Credit(s)","","","","","$0.00",""
"08/31/2017","","","Redacted","$18.76","",""
"08/31/2017","","","Redacted","$12.27","",""
"Posted Transactions"
"08/31/2017","INTADJUST","","Interest Paid","","$0.07","$210.72"
"08/31/2017","ATMREBATE","","ATM Fee Rebate","","$1.77","$392.69"
"08/31/2017","","","Redacted","$12.27","",""

Note that there's another header row in the middle somewhere, how will we handle that?

**Comment by nocalla** [comment]
It'll get ignored because the row doesn't have an inflow.

**Comment by torbengb** [comment]
I've added it to the config, with the user comment as discussed.

**Comment by sshumate** [comment]
The filename for Schwab Bank accounts are similar to these:

> XXXXXX111111_Savings_Transactions_20200324-000000.CSV
> XXXXXX111111_Checking_Transactions_20200324-000000.CSV

The "XXXXXX111111" is the account number with the first half X'd out. Following the checking/savings transactions is the date. I'm not sure what the "000000" on the end is, but I've changed it to 0's in case it's some form of identifier. The pattern and configuration information I used in my file to get this to function are as follows:

`Source Filename Pattern = XXXXXX[0-9]{6}_(Checking|Savings)_Transactions_[0-9]{8}-[0-9]{6}`
`Source Filename Extension = .CSV`
`Use Regex for Filename = True`

Thanks for your project. Hope this helps.

**Comment by nocalla** [comment]
Thanks @sshumate, that's really helpful. I might actually make two separate configs for this bank, one for checking and one for savings. Can you confirm if the input columns and date format match @torbengb's comment above?

**Comment by sshumate** [comment]
You're welcome. I'm glad it was helpful! Yes, I can confirm the input columns match @torbengb 's post and I've been using it with the information from a combination of his and my posts since March. 

You may eventually need a third configuration for investment accounts that Schwab Bank supports, but I looked at those files and they are a completely different format. I can provide information about those as well if you'd like, but I don't include those in my budget so I haven't been using them with YNAB.

**Comment by nocalla** [comment]
Great news. Thanks for your help. If you have the details for that 3rd account, by all means share them, but no pressure.

**Comment by sshumate** [comment]
Upon further review, I'm not even sure the format can be made compatible with YNAB. It looks like the export is always a list of current positions held on investments rather than transaction data. I've attached a blank/empty CSV (converted to txt so I can upload to GitHub) as exported from Schwab with only my account number changed in case you can piece together more than I have. Let me know if there's any more information I can provide that might help.

[Individual-Positions-2020-07-09-114416.txt](https://github.com/bank2ynab/bank2ynab/files/4897926/Individual-Positions-2020-07-09-114416.txt)

Note: the 114416 in the filename appears to be hhmmss of the time I hit export. It's not account information.

**Comment by nocalla** [comment]
Yeah, I think you're right - I don't see how that can be made into a YNAB-friendly transaction file realistically. Thanks for the input regardless though!
