### ISSUE TITLE
Support for Banco Bradesco [BR]

### ISSUE THREAD

**Issue by nocalla** [bank2ynab/bank2ynab#135]
Name of Bank: Banco Bradesco
Country: Brazil [BR]

Source: [pedroaxl/ynab-scripts](https://github.com/pedroaxl/ynab-scripts)

**To be filled in as required. Delete fields that match default values.**
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Plugin =

Master issue #21

**Comment by angelod1as** [comment]
Can I ask why was this removed? It doesn't show in the README list. Is it included or not? Thanks a lot.

**Comment by nocalla** [comment]
Hi, thanks for your interest. This was removed due to insufficient information being available. If you can provide information about the format of the export file, we can support it. 
We need:
- Source Filename or regex pattern
- Source Filename Extension 
- Source CSV Delimiter
- Source Has Column Headers 
- Source Columns as they map to YNAB

**Comment by angelod1as** [comment]
OK, I'll read through the docs to understand what I need to do and I'll come back with suggestions.

**Comment by nocalla** [comment]
If you look at the `bank2ynab.conf` file that will show you examples of other banks.

**Comment by angelod1as** [comment]
OK, I tried doing it but the CSV generated by the bank has issues. I'll paste a sample below with different data but same structure so you can see what I'm talking about (and maybe help me fixing it).

I'd love to open a PR with this and collaborate with more banks (I have a Branco do Brasil and a Nubank account) but I need to get this one sorted out first.

```csv
Extrato de: Ag: 111 | Conta: 11111-1 | Entre 01/10/2023 e 31/10/2023
Data;Hist�rico;Docto.;Cr�dito (R$);D�bito (R$);Saldo (R$);
09/03/23;SALDO ANTERIOR;;;;"0,03";
05/10/23; Ted-t Elet Disp;2638235;"7.500,00";;"7.500,03";
;Remet.foo bar;;
;Total;;"7.500,00";"0,00";"7.500,03"
Os dados acima t�m como base 10/10/2023 �s 20h58 e est�o sujeitos a altera��es.

�ltimos Lan�amentos
Data;Hist�rico;Docto.;Cr�dito (R$);D�bito (R$);
05/10/23;SALDO ANTERIOR;;;;
09/10/23; Transferencia Pix;1111111;"7.500,00";;
;Rem: foo bar 09/10;;
09/10/23; Pagto Eletron  Cobranca;1111111;;"-1.255,31";
;Transferencia ABC;;
09/10/23; Pagto Eletron  Cobranca;1111111;;"-1.339,00";
;Transferencia DEF;;
09/10/23; Transferencia Pix;1111111;;"-1.090,00";
;Des: foo bar 09/10;;
10/10/23; Conta de Gas;1111111;;"-43,79";
10/10/23; Conta de Luz;1111111;;"-196,03";
10/10/23; Conta de Telefone;1111111;;"-123,25";
10/10/23; Transferencia Pix;1111111;;"-531,20";
;Des: foo bar 10/10;;
;Total;;"7.500,00";"-4.578,58"
```

According to this CSV above, I can answer (based on the `bank2ynab.conf`:

```bash
[BR Bradesco, checking]
# Bradesco_10102023_205851.csv
Source Filename Pattern = Bradesco_ # I don't know if I should write more here
Source Filename Extension = .csv
Use Regex for Filename = False # I don't know if this is correct
Source CSV Delimiter = ;
Header Rows = 10 # Here I tried to measure how many "non-relevant" rows there are before the real data. I don't know for sure if this number is stable of it changes.
Footer Rows = 0
Input Columns = Date,Payee,skip,Inflow,Outflow,skip,Memo # See comment below
Date Format = %d/%m/%Y
```

For the import columns, from the sample:

```csv
09/10/23; Pagto Eletron  Cobranca;1111111;;"-1.255,31";
;Transferencia ABC;;
```

This could be, actually, this:

```csv
09/10/23; Pagto Eletron  Cobranca;1111111;;"-1.255,31";;Transferencia ABC;;
```

Because it's from the same transaction.

At the same time, this is valid:

```csv
10/10/23; Conta de Telefone;1111111;;"-123,25";
```

as it doesn't have a Memo.

ON THE OTHER HAND, I have the OFX file from this bank and I don't know how to add it to the code and open a PR ([see here please](https://github.com/bank2ynab/bank2ynab/issues/274#issuecomment-1756493963), I also don't know how to test locally, sorry).

The OFX file is quite clean and straightforward. One example below:

``ofx
<BANKTRANLIST>
	<DTSTART>20231001000000
	<DTEND>20231031000000
	<STMTTRN>
		<TRNTYPE>CREDIT
		<DTPOSTED>20231005000000[-03:EST]
		<TRNAMT>7500.00
		<FITID>N20131:05/10/23:7500.0:2638235: Ted-t Elet Disp: Remet.lorem
		<CHECKNUM>1111111
		<MEMO>Ted-t Elet Disp Remet.lorem
	</STMTTRN>
	<STMTTRN>
		<TRNTYPE>CREDIT
		<DTPOSTED>20231009000000[-03:EST]
		<TRNAMT>7500.00
		<FITID>N20022:09/10/23:7500.0:1543041: Transferencia Pix: Rem: lorem ipsum 09/10
		<CHECKNUM>1111111
		<MEMO>Transferencia Pix Rem: lorem ipsum 09/10
	</STMTTRN>
</BANKTRANLIST>
```

The whole OFX is [here](https://pastebin.com/KdefQgmg).

**Comment by nocalla** [comment]
The filename is easy enough, it seems to follow the pattern of "Bradesco_ddmmyyyy_xxxxxx.csv", so we can use a regex to identify the file based on that pattern of the initial text followed by 8 and 6 digits with separators. 

```
[BR Bradesco, checking]
# Bradesco_10102023_205851.csv
Use Regex For Filename = True
Source Filename Pattern = Bradesco_[0-9]{8}_[0-9]{6}
Source CSV Delimiter = ;
Header Rows = 10
Footer Rows = 0
Input Columns = Date,Payee,skip,Inflow,Outflow,skip,Memo
Date Format = %d/%m/%Y
```

I don't understand your point with the three different examples though, a CSV file should have a single entry per row and has to leave blank entries if there is an entry missing, e.g. no memo, so in your case this would look like ";;".  

This project does not work with OFX files.

**Comment by angelod1as** [comment]
About the OFX: I had misunderstood the docs (sorry, I've got COVID and it's killing my brain). You are correct, there was no need to even mention OFX.

About the three examples: the bigger chunk of code is exactly the problem, that's how the CSV was exported from their website — without 1 entry per line, but with some split in two lines. Couldn't that be a problem for your program? I mean, we delimit that the first element in every row is (e.g.) Date, and then there are these two different lines:

```
09/10/23; Transferencia Pix;1111111;"7.500,00";;
;Rem: foo bar 09/10;;
```

The first one is parsed correctly and understood. The second one, though, is not. That's because they should be _one line_ and the bank exports it incorrectly.

My point here is: maybe this bank is impossible to be integrated into your application because of this quirk. That's what I meant.

**Comment by nocalla** [comment]
So it's not consistent, I.e. can we drop every second row, or is it just for longer lines or is it random? (And is it definitely not line wrapping kicking in for your text editor?)

**Comment by angelod1as** [comment]
@nocalla sadly not consistent :(

And definitely not my text editor, I opened it straight after exporting in both vscode, textedit and numbers, and all of them are weird.

**Comment by nocalla** [comment]
Sounds like something we need to fix by pre-processing the file, which is simple enough. What logic would it take to get each transaction on to a single row? E.g.: remove every line break that isn't followed by a number.

**Comment by angelod1as** [comment]
I'd say: remove the line break if the first character is a `;`, as the line should always start with a date.

```
09/10/23; Transferencia Pix;1111111;"7.500,00";;
;Rem: foo bar 09/10;;
09/10/23; Pagto Eletron  Cobranca;1111111;;"-1.255,31";
;Transferencia ABC;;
09/10/23; Pagto Eletron  Cobranca;1111111;;"-1.339,00";
;Transferencia DEF;;
```

**Comment by nocalla** [comment]
Try out the code in #447 and see if it works for you.

**Comment by nocalla** [comment]
Any luck with the code in #447, @angelod1as?

**Comment by angelod1as** [comment]
Worked like a charm :)
