### ISSUE TITLE
How do I add a pre-commit hook?

### ISSUE THREAD

**Issue by torbengb** [bank2ynab/bank2ynab#181]
it should go into the file:
bank2ynab/.git/hooks/pre-commit but when I added that, it ended up as:
bank2ynab/hooks/pre-commit

**Comment by nocalla** [comment]
Hook tutorial here: https://www.atlassian.com/git/tutorials/git-hooks. 

A key paragraph: Maintaining hooks for a team of developers can be a little tricky because the .git/hooks directory isn’t cloned with the rest of your project, nor is it under version control. A simple solution to both of these problems is to store your hooks in the actual project directory (above the .git directory). This lets you edit them like any other version-controlled file. To install the hook, you can either create a symlink to it in .git/hooks, or you can simply copy and paste it into the .git/hooks directory whenever the hook is updated.

Hooks executing during the commit creation process
As an alternative, Git also provides a Template Directory mechanism that makes it easier to install hooks automatically. All of the files and directories contained in this template directory are copied into the .git directory every time you use git init or git clone.

**Comment by nocalla** [comment]
What are you trying to do?

**Comment by torbengb** [comment]
> What are you trying to do?

In #180 I wanted to integrate the branch into the version string, so we can see when we run the tool that we've got e.g. `bank2ynab 1.1.0-dev` or `bank2ynab 1.1.0-somefeaturebranchname`. The master would just show `1.1.0`. 

To do this, the resources I found read the HitHub tag. Still toying with it, figuring it out as I go.

**Comment by nocalla** [comment]
Working on this. Mostly to add some nice auto-formatting, as per [this post](https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/). Travis will be so pleased.

**Comment by torbengb** [comment]
That is so neat!! _Man_ I've been so upset in the past about never-ending flake8 errors so I love this initiative. (I'm impressed: there's always _someone_ on the Internet who's already solved whatever problem one could be facing. Long live the free and open Internet.)

It would be sweet if everyone had access to that, and if everyone committed(pun!) to using it. Do we need to add mandatory requirements for contributors, such as installing and running that?

**Comment by nocalla** [comment]
Added pre-commit config file to Develop. Documentation is over here: https://pre-commit.com/

Works very well for those "never-ending flake8 errors", @torbengb!

**Comment by nocalla** [comment]
See #308 for what we're doing instead! Closed.
