### ISSUE TITLE
Cleanup of transaction Names for better YNAB categorization

### ISSUE THREAD

**Issue by duch11** [bank2ynab/bank2ynab#260]
**Problem: Transactions with numbers or ID's of some sort, confuses YNAB.**
When I import transactions like:
```
DK-NOTA5207 BASTARD CAFE 
DK-NOTA5076 BASTARD CAFE 
```

YNAB doesn't recognize that it's the same payee, this might be an isolated issue to Danish Transactions. IDK But it annoys the heck out of me and my GF, that we have to reassign the same categories all the time.

**Describe the solution you'd like**
I would like to add an option to scrub the names of transactions clean of patterns like 

`DK-NOTAxxxx`

Then save the original transaction name in a "note" field (I'm not sure if YNAB imports support such a field, but if it does, it would be nice.)

Maybe have it tied to specific banks or countries, or start making a blacklist of patterns to remove, for portability.

**Describe alternatives you've considered**
A dictionary, for improved naming of transaction.

NamingPattern: PrettyName 

It might be overkill, but it would be cool. Maybe there already is a database of some sort of transaction names and their prettified version? 

I'm thinking something like how certain mobile only banking solutions does it 
( Apple Pay, Lunar way.)
![Screenshot from 2019-03-26 15-44-27](https://user-images.githubusercontent.com/17031368/55006477-1da1fc80-4fde-11e9-9024-2871846bb11b.png)

**Additional context**
https://lunarway.com/

**Comment by nocalla** [comment]
This is actually something handled by default in the Manage Payees section of YNAB. You can set it so that any transaction with a payee containing "Bastard Cafe" gets renamed to whatever you want.

**Comment by nocalla** [comment]
This is actually something handled by default in the Manage Payees section of YNAB. You can set it so that any transaction with a payee containing "Bastard Cafe" gets renamed to whatever you want.

**Comment by torbengb** [comment]
Hejsa Jonas!
I know your pain, and it's not just Danish banks that have that kind of
payees. Luckily, "bank2ynab" doesn't need to do anything because this is
already handled in YNAB itself! Are you familiar with YNAB's payee
management <https://docs.youneedabudget.com/article/611-payee-management>?
For your specific problem, have a look at the section "automatically rename
payees
<https://docs.youneedabudget.com/article/611-payee-management#addandedit>."
I use that extensively and I think you can use it too, for instance have a
rule for a payee "Bastard Cafe" that automatically assigns this payee to
your "going out" category and *matches any payee *that *contains* the
phrase "bastard cafe", for instance.

Let me know what you think!
Mange hilsener fra Østrig.

**Comment by duch11** [comment]
OMG thank you! Didn't know anything about that feature!
