### ISSUE TITLE
2.0 website to drag'n'drop a CSV file and have it upload into YNAB automagically

### ISSUE THREAD

**Issue by torbengb** [bank2ynab/bank2ynab#266]
This idea is completely different from a command-line tool on the user's local computer, but you could view it as an evolution.

----

Imagine a website that basically just says "drop a CSV file here" and it would then detect the bank format, convert to YNAB CSV, and usethe YNAB API to send the data straight into your budget. As a a user, you'd be done in a second!

Of course a new user would first have to enter their API key (and perhaps their preferences) so they don't have to provide it again every time.

Preferences:  
I think there's no way around having to ask the user every time what account to write the transactions into. (I have two accounts at two banks = one in each = easy to tell apart. But if I had two accounts at the same bank = same file format = can't predict which account the export is from.)

User profile:  
We could store the API key and favorite budget in a browser cookie. That avoids having the whole nasty concept of "user accounts", but with the downside of being fragile: cookies don't live long in the wild. So I guess user accounts are a fact, and we should use some existing library for this.

Background tech:  
For this we need web skills that we haven't used in this project yet. I'm unsure whether my own skills are sufficient, as they are a bit dated. It's easy to create a website, but integrating user accounts and a server-side Python backend process to run our original (and likely adapted) bank2ynab script is a different beast.  
We can also host web pages right here on Github, but I wonder whether we can make it run a Python backend too.

----

We should probably spin all of this off into a separate Github project. Ideally, the current project could be a drop-in service for that. 

(edit: renamed from 3.0 to 2.0)

**Comment by duch11** [comment]
I think django might be the framework of choice, if we want easy user authentication. It "should" be able to fix all that setup in minutes.. I have no experience with it, but I've heard good things. I think it might be using MVC, so in that regard it should be easy enough.

**Comment by duch11** [comment]
I've been developing a node backend and angular frontend for YNAB sync, last year. (with no ynab sync at all, if you can believe it)
I might be able to port it to a django project some day, I just need to find more free time in the calendar before this can happen. But I might be able to do it, especially if django is as plug and play as they say.

**Comment by nocalla** [comment]
I don't have this skill set, I'm afraid.

**Comment by torbengb** [comment]
For the record, I have access to good free hosting that supports Python out of the box over at [DreamHost.com](https://www.dreamhost.com/r.cgi?39038). Python v3.6.7 and 2.7.15 are already [installed](https://help.dreamhost.com/hc/en-us/articles/216137717-Python-overview), and we can install [any version](https://help.dreamhost.com/hc/en-us/articles/115000702772-Installing-a-custom-version-of-Python-3) we want.

**Comment by leolabs** [comment]
I've managed to implement a part of that (automatic uploading to YNAB is missing) in the past few weeks. My tool is called [You Need A Parser](https://ynap.leolabs.org). Its source code is available [here](https://github.com/leolabs/you-need-a-parser). I've managed to do the complete process on the client, without needing a server, so no data will ever leave the browser.

**Comment by duch11** [comment]
Hello everyone,
@leolabs amazing frontend parser looks so rad! I just wished it was better incorporated with the functionality we are developing here on this project. 
I feel like the drag and drop idea kinda died when somebody already did it, but I think it should be celebrated, and connected together somehow! 

Can we make that happen somehow?
What is your thoughts?
Especially any ideas from you @leolabs would be great, as you know of the inner workings of your frontend, do you think it could be done, maybe with an added backend?
I would love to work together on an implementation that would fit any spec you would define :)

**Comment by leolabs** [comment]
Hey @duch11,
thanks for mentioning me!

My project is split into three parts:

- [ynap-web-app](https://github.com/leolabs/you-need-a-parser/tree/master/packages/ynap-web-app), which is what you see on [ynap.leolabs.org](https://ynap.leolabs.org)
- [ynap-parsers](https://github.com/leolabs/you-need-a-parser/tree/master/packages/ynap-parsers), the library that does the actual parsing and conversion
- [ynap-bank2ynab-converter](https://github.com/leolabs/you-need-a-parser/tree/master/packages/ynap-bank2ynab-converter), which can convert a bank2ynab configuration file into a JSON file that is readable by ynap-parsers

You Need A Parser (YNAP) already uses the configurations provided by bank2ynab, so every file that can be converted by bank2ynab can also be converted by YNAP. 

In general, I don't think it's necessary to add a backend to a project like this because browsers are powerful enough to do the conversion themselves. YNAP does this already, the whole conversion process takes place in the browser. This also means that no data ever leaves the computer which I think is important when we work with users' bank statements.

To make the importing process easier, it would be nice to have the functionality of ynap-parsers directly integrated into YNAB's web app, for example by integrating it into YNAB Toolkit. I've opened an [issue](https://github.com/toolkit-for-ynab/toolkit-for-ynab/issues/1566) on their repo a few months ago but didn't get a response yet. If all else fails, developing a separate Chrome plugin might be an idea. That way, users would be able to just drag their bank's exported statements into YNAB and have them be converted before they're imported.

Regarding the possible gains:

- Making the import process easier would be awesome!
- Regarding the "more robust conversion", I think that ynap-parsers is at least on par with bank2ynab robustness-wise. The project includes 16 test suites with a total of 92 tests (95% code coverage) to make sure that the format conversions are executed correctly. Due to the project structure, ynap-parsers can do more than just extract fields from CSV files. For example, comdirect's CSV format puts multiple bits of information into one big CSV field. The [parser](https://github.com/leolabs/you-need-a-parser/blob/master/packages/ynap-parsers/src/de/comdirect/comdirect.ts#L52-L78) is able to extract those.
- I'd love to see both efforts being combined! One hurdle I see is the difference in languages (Python / TS) and the project structure (configuration file / parser scripts). It would be nice if we could overcome this.

Let me know what you think the next steps could be.

**Comment by nocalla** [comment]
I think we should abandon this idea for now in favour of automating the config conversion to JSON as mentioned by @leolabs with a Github Action. I've made an issue for that over here at #319. We can always re-open discussion on this if a compelling reason for us to tackle this arises.
