### ISSUE TITLE
Bank to add - Neteller

### ISSUE THREAD

**Issue by PancakeZik** [bank2ynab/bank2ynab#268]
I've made the configuration for Neteller.com but I'm not very good in github, so if you could please add this to the project:

[NETELLER]
Source Filename Pattern = NETELLER_transaction_history
Source Filename Extension = .csv
Use Regex For Filename = True
Header Rows = 1
Footer Rows = 0
Source CSV Delimiter = ,
Input Columns = skip,skip,skip,Payee,Date,skip,Inflow,skip,skip,skip,skip,skip,skip,skip,skip,skip,skip,skip
Date Format = %d-%m-%Y / %H:%M

Thank you very much.

**Comment by torbengb** [comment]
Hi Pancake! No problem at all, happy to add it for you. Some questions though:

- You said "True" to Regex but the filename seems to be a fixed text "NETELLER_transaction_history" so I would say "False". Is there anything in the filename that would change from one export to another?
- Neteller seems to be mainly a UK operation, is that right? Or would you rather call it a piece of software? This is just to help us categorize it better.

I'm thinking that just three lines would be sufficient, because the rest equals the default settings. Does this look right to you?
```
[UK NETELLER]
Source Filename Pattern = NETELLER_transaction_history
Input Columns = skip,skip,skip,Payee,Date,skip,Inflow,skip,skip,skip,skip,skip,skip,skip,skip,skip,skip,skip
Date Format = %d-%m-%Y / %H:%M
```

**Comment by PancakeZik** [comment]
Hi there,

Thanks for the quick reply. I don't think you should count it as UK since
its basically global.
The rest of the config seems fine the way you wrote it, thank you so much!

**Comment by torbengb** [comment]
Thank you for the confirmation. With your help, we now support 52 different formats!

I've now included it in the code and you can download a brand-new developer copy here: https://github.com/bank2ynab/bank2ynab/archive/develop.zip
