### ISSUE TITLE
Extraction of transaction information from the memo

### ISSUE THREAD

**Issue by Pezmc** [bank2ynab/bank2ynab#411]
**Other feature request**

**Is your feature request related to a problem? Please describe.**
Some of my bank accounts put all of the useful information (actual transaction date, description, payee, etc) in the memo field. This means that using bank2ynab as it stands results in data in YNAB like:

> Date: 2021-12-22 (the settle date not transaction date)
> Payee: ""
> Memo: PAYMENT VIA MAESTRO                  22-12 21-12-2021 AT 17.00 TIME MCDONALDS AEROP LISB 1500-284 WITH APPLE PAY XX XXXX X6 VIRTUAL CARD FOR CONTACTLESS: XXXX X888 9 CARDHOLDER: NAME HERE

**Describe the solution you'd like**

I'd like a built in way (perhaps via a .conf file) to extract information from this memo field, it could be perhaps a regex that documents the format, then information from the memo, rather than the CSV's other rows, are used in YNAB.

**Describe alternatives you've considered**

Manually, or automatically before bank2ynab processing, clean up all the data.

**Additional context**

The biggest difficulty is not all banks seem to do this, and they'll all have widely different formats. Whatever solution is implemented it needs to avoid being brittle.

Would you accept a pull request implementing such a feature? (if I have the time).

**Comment by nocalla** [comment]
We would absolutely accept a pull request implementing this feature. 

This should be relatively straightforward to do using the plugin setup we have. It could be a fairly generic "extract_info_from_memo.py" file, with something like the memo column, regex, and data order within the regex output specified as a list of plugin arguments. 

See the `plugins/pdf_converter.py` file for an example of how the preprocess_file function is used. You'd probably extract the memo information and output it as a CSV, passing the new filename back for the rest of the script to act on. Try to keep the processing as minimal as you can in the plugin so that it stays fairly general purpose.
