### ISSUE TITLE
Feature request: Add setting to delete fixed statement file after API upload 

### ISSUE THREAD

**Issue by jenseo** [bank2ynab/bank2ynab#455]
This is not really a feature request but more of a question, although it could be a feature request in the sense that it would be nice with a flag that removes successfully uploaded statements via the API. But that depends on if it aligns with my question or not 😄 

Anyways, I use the YNAB api for uploading statements and it works fantastically well, so thank you for that! But my question is, is it YNAB that keeps track of transactions that has already been uploaded or is it the old statements? Prefixed with the default **fixed_** in my case.

It would be nice to be able to remove those, but I want to make sure that I won't get duplicates in YNAB doing so. Also, if it's not a problem removing it, the flag to do it automatically would indeed be sweet 😄 

Thanks again for an invaluable tool that I really enjoy. I also set up a Playwright script that takes care of visiting my bank, let me log in and downloads all statements I need in a couple of seconds. Combined with your script, it doesn't take more than 8 seconds or so to download my statements and sync them with YNAB. Awesome! 🤩

**Comment by nocalla** [comment]
This would require the addition of an extra conf flag as it's not currently supported. You can auto delete the original downloaded statement (and that's actually the default behaviour) but not the "fixed" version. You can certainly delete the fixed files manually though without worrying about duplicates.

**Comment by torbengb** [comment]
Let me also address this part: "is it YNAB that keeps track of transactions
that has already been uploaded?"

Yes, that is YNAB's pattern-matching at work. `bank2ynab` doesn't know
whether the new CSV file contains entries that already exist in YNAB; that
could happen from an earlier import, or from a manual entry. Because of
YNAB's matching, there's no harm in delivering existing transactions to
YNAB; they will be recognized and ignored. After `bank2ynab`has finished
running, it is safe to delete both the original CSV and the "fixed_"
version.

We might consider whether to delete the "fixed_" file automatically, like
we do with the input CSV.

**Comment by nocalla** [comment]
Let's keep this open as a feature request. We can do this relatively easily once I get a bit of coding time.

**Comment by nocalla** [comment]
Try out the branch over on #456 @jenseo and let me know if it works for your use case. Just add `Save Output File = False` to your user config.

**Comment by jenseo** [comment]
> Try out the branch over on #456 @jenseo and let me know if it works for your use case. Just add `Save Output File = False` to your user config.

Sorry for the late reply, I didn't see this notification until now! Works great!
